# discover configurations
[discover]
    # server name
    name =              "nanos world server"
    # server description (max 127 characters)
    description =       ""
    # server IP. we recommend leaving it 0.0.0.0 for default
    ip =                "0.0.0.0"
    # server port (TCP and UDP)
    port =              7777
    # query port (UDP)
    query_port =        7778
    # announce server in the master server list
    announce =          true
    # true if should run as dedicated server or false to run as P2P - dedicated server requires port forwarding and provides the fastest connection - P2P will provide a fake IP to be used to connect but connection can be slower as it uses Steam Datagram Relay service
    dedicated_server =  true

# general configurations
[general]
    # max players
    max_players =       64
    # leave it blank for no password
    password =          ""
    # nanos world server authentication token
    token =             ""
    # banned nanos account IDs
    banned_ids = [

    ]

# game configurations
[game]
    # default startup map
    map =               "default-blank-map"
    # game-mode package to load (set the main game-mode package to load - you can load only one 'game-mode' package type at once)
    game_mode =         ""
    # packages list (set the packages you want to load)
    packages = [

    ]
    # asset packs list (additionally loads the asset packs you define here)
    assets = [

    ]
    # loading-screen package to load (the loading screen will be displayed when players join your server)
    loading_screen =    ""

# custom settings values
# those values can be accessed through Server.GetCustomSettings() method from any package
[custom_settings]
    # my_setting_01 = "value"
    # my_setting_02 = 123

# debug configurations
[debug]
    # log Level - (1) normal, (2) debug or (3) verbose
    log_level =         1
    # if to use async or sync logs (async provides better performance, disabling async logs can help debugging crashes)
    async_log =         true
    # enables performance profiling logs for debugging
    profiling =         false

# optimization configurations
[optimization]
    # server max tick rate in Hz (ticks per second). Higher = more responsive but uses mor CPU. 30 Hz = 33ms per tick (default and recommended). Use with caution
    max_tick_rate =     30
    # max send rate per client in MB/s - limits bandwidth for each connected player (1 - 32) - this only affects Dedicated Servers as P2P is naturally limited to 1 MB/s by Steam Datagram Relay service
    max_send_rate =     16
    # sets the compression level to use in some networking operations (0 - 9) - (0) disables it, (1) is the fastest and (9) is the slowest but has the highest compression ratio
    compression =       0
